### ISSUE TITLE
gfortran and libquadmath bundled

### ISSUE THREAD

**Issue by rgommers** [MacPython/numpy-wheels#42]
This should no longer be needed now that we're shipping wheels with OpenBLAS. And it's an actual problem, here's a report of a user that ran into a gfortran runtime incompatibility: https://mail.python.org/pipermail/numpy-discussion/2019-January/079151.html

Let's try to fix this before the next release.

**Comment by mattip** [comment]
From the linked mail the problem manifests itself on MacOS. Is this also a problem for linux and windows builds?

**Comment by tylerjereddy** [comment]
This should be solvable for MacOS as I demonstrated with https://github.com/numpy/numpy/pull/13191

Should be the same static vs. dynamic situation on the other platforms, yes.

**Comment by tylerjereddy** [comment]
I don't get the reasoning here--OpenBLAS has runtime dependencies on the shared libraries that are packed in the wheel & that are causing that user problems. Including those runtime dependencies seems to be similar to PEP 513 / auditwheel-style workflows?

You want to remove those supporting libraries and assume that downstream systems will always have the gcc / gfortran runtime dependencies needed for OpenBLAS?

> auditwheel has the ability to automatically modify wheels that depend on external shared libraries by copying those shared libraries from the system into the wheel itself

**Comment by rgommers** [comment]
> OpenBLAS has runtime dependencies on the shared libraries

I seemed to remember a Fortran compiler wasn't necessary for OpenBLAS. Turns out my memory was wrong/incomplete, it's an optional dependency:  https://github.com/xianyi/OpenBLAS#dependencies. We need those optional bits (= most of LAPACK), so the "should no longer be needed" is just wrong.

Closing.

**Comment by marcpaterno** [comment]
This is the original reporter of the issue, returning to it. I have been unable to produce a small example demonstrating the failure I see when running my real application. However, for that application, if I build numpy in the virtual environment I use for the other Python packages used (rather than using 'pip install numpy'), using the appropriate site.cfg to allow my Homebrew-installed openblas to be found, I obtain a numpy that has no embedded copy of any dynamic libraries. My program then runs without a problem. If, instead, I use 'pip install numpy', my program reliably crashes in a call to the Fortran date_and_time intrinsic, caused by the ABI mis-match.

So, on macOS, to use numpy in projects that also use other Fortran code, I have to build numpy. Instructions for my users would be notably simpler if I could tell them to use 'pip install numpy'.

If anyone is interested in helping me create a small reproducible example, I would be most appreciative.
